name: Release

on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]

jobs:
  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: npm

    - name: Install Dependencies
      run: npm ci

    - name: 🔨 Build Binaries
      run: npm run build

    - name: Create Github Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build/*"
        token: ${{ secrets.GITHUB_TOKEN }}
